codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        informational: true
    patch:
      default:
        target: 80%
        threshold: 1%
        informational: true

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false

ignore:
  - "packages/*/test/**/*"
  - "packages/*/dist/**/*"
  - "scripts/**/*"
  - "**/*.test.ts"
  - "**/*.spec.ts"
  - "**/*.d.ts"

flag_management:
  default_rules:
    carryforward: true
  individual_flags:
    - name: extension
      paths:
        - packages/extension/
    - name: mcp-server
      paths:
        - packages/mcp-server/
